name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: main
      shell: cmd
      run: |
        set PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;C:\Program Files\7-Zip;C:\Program Files\NASM;%PATH%
        call vcvars64.bat
        curl -L -o openssl-3.5.1.tar.gz https://github.com/openssl/openssl/releases/download/openssl-3.5.1/openssl-3.5.1.tar.gz
        7z x -y openssl-3.5.1.tar.gz
        7z x -y openssl-3.5.1.tar
        choco install nasm
        pushd openssl-3.5.1
            perl Configure --prefix=C:/openssl-3.5.1
            nmake
            nmake install
        popd
        7z a -y openssl-3.5.1.zip C:\openssl-3.5.1
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: openssl-3.5.1
        path: C:/openssl-3.5.1
    - name: release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: openssl-3.5.1.zip
