name: main
on: push
jobs:
  main:
    strategy:
      matrix:
        msystem: [MINGW64, MINGW32]
      fail-fast: false
    runs-on: windows-2022
    steps:
      - run: |
          echo CHERE_INVOKING=yes>> %GITHUB_ENV%
          echo MSYSTEM=${{ matrix.msystem }}>> %GITHUB_ENV%
          echo BASH=C:\msys64\usr\bin\bash>> %GITHUB_ENV%
          if "${{ matrix.msystem }}" equ "MINGW32" echo MSYSTEM_=mingw32>> %GITHUB_ENV%
          if "${{ matrix.msystem }}" equ "MINGW64" echo MSYSTEM_=mingw64>> %GITHUB_ENV%
        shell: cmd
        name: prepare env

      - run: |
          %BASH% -lc "pacman --noconfirm -Syuu"
          %BASH% -lc "pacman --noconfirm -Syuu"
        shell: cmd
        name: update msys2

      - run: |
          if "${{ matrix.msystem }}" equ "MINGW32" (
          %BASH% -lc "pacman -S --needed --noconfirm base-devel mingw-w64-i686-toolchain zip make"
          ) else (
          %BASH% -lc "pacman -S --needed --noconfirm base-devel mingw-w64-x86_64-toolchain zip make"
          )

        shell: cmd
        name: install mingw toolchain and tools

      - run: |
          curl -L -o openssl-1.1.1n.tar.gz https://www.openssl.org/source/openssl-1.1.1n.tar.gz
          %BASH% -lc "tar xf openssl-1.1.1n.tar.gz"
        shell: cmd
        name: download and unzip sources

      - run: |
          pushd openssl-1.1.1n
            %BASH% -lc './config --prefix="%CD%/../OpenSSL" --openssldir=ssl'
            %BASH% -lc "make install"
          popd
        shell: cmd
        name: build and install

      - run: |
          %BASH% -lc "zip -r OpenSSL-1.1.1n-%MSYSTEM_%.zip OpenSSL"
        shell: cmd
        name: zip package

      - uses: softprops/action-gh-release@v1
        with:
          files: OpenSSL-1.1.1n-%MSYSTEM_%.zip
        if: startsWith(github.ref, 'refs/tags/')
        name: release